FROM cowrie/cowrie:latest

# Change to 22 and 23 + modify docker compose when setup with firewall
EXPOSE 2222
EXPOSE 2223 

COPY cowrie.cfg /cowrie/cowrie-git/etc/cowrie.cfg
# COPY test.txt /cowrie/cowrie-git/etc/test.txt

